# .circleci/config.yml
orbs:
  macos: circleci/macos@2
version: 2.1
jobs:
  build-and-test:
    resource_class: m4pro.medium
    macos:
      xcode: 16.4.0
    steps:
      - checkout
      - run:
          name: Submodule sync & update
          command: git submodule sync --recursive && git submodule update --recursive --init
      - run:
          name: Fastlane test
          command: fastlane test

  release:
    resource_class: m4pro.medium
    macos:
      xcode: 16.4.0
    steps:
      - checkout
      - run:
          name: Submodule sync & update
          command: git submodule sync --recursive && git submodule update --recursive --init
      - run:
          name: Fastlane release
          command: fastlane release build_number:<< pipeline.number >>

workflows:
  build-test-release:
    jobs:
      - build-and-test
      - release:
          filters:
            branches:
              only:
                - main
                - test
              
          #requires:
          #  - build-and-test
