# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: 15.3.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      - run:
          name: Fastlane
          command: fastlane scan --scheme "CarePartner" --device "iPhone 15" --clean 

  release:
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: 15.2.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: release
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      - run:
          name: Fastlane
          command: fastlane release build_number:<< pipeline.number >>
          no_output_timeout: 20m

workflows:
  build-test-release:
    jobs:
      - build-and-test
      - release:
          filters:
            branches:
              only: main
          requires:
            - build-and-test
