# .circleci/config.yml
orbs:
  macos: circleci/macos@2
version: 2.1
jobs:
  build-and-test:
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: 16.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      - run:
          name: Fastlane
          command: fastlane scan --scheme "CarePartner" --device "iPhone 16" --clean

  release:
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: 16.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: release
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --recursive --init
      - run:
          name: Fastlane
          command: fastlane release build_number:<< pipeline.number >>

workflows:
  build-test-release:
    jobs:
      - build-and-test
      - release:
          filters:
            branches:
              only:
                - main
                - test
              
          requires:
            - build-and-test
